<?php
/**
 * @file
 * file contains functionality for unblocking the user in view bulk opertions
 */
/**
 * implementing hook_action_info();
 */
function la_custom_action_info() {
  return array(
    'la_custom_unblock_user_action' => array(
      'label' => t('Unblock the user'),
      'type' => 'user',
      'configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}
/**
 * 
 */
function la_custom_unblock_user_action(&$entity, $context = array()) {
  // First priority: If there is a $entity->uid, unblock that user.
// This is most likely a user object or the author if a node or comment.
  if (isset($entity->uid)) {
    $uid = $entity->uid;
  }
// Otherwise get user ID from the context.
  elseif (isset($context['uid'])) {
    $uid = $context['uid'];
  }
  $account = user_load($uid);
  $account = user_save($account, array('status' => 1));
  watchdog('action', 'Unblocked user %name.', array('%name' => $account->name));
}
